---
--- Generated by Luanalysis
--- Created by MaQi.
--- DateTime: 2024/5/20 22:46
---
-- 1.定义变量
-- 1.1 优惠券id
local voucherId = ARGV[1]
local userId = ARGV[2]

-- 2. 数据key
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
-- 3.1 判断库存是否充足
if (tonumber(redis.call('get', stockKey))<=0) then
    -- 3.2 库存不足，返回1
    return 1
end

-- 3.2 判断用户是否下单
if(redis.call('sismember', orderKey, userId) == 1) then
    -- 3.3 重复下单，返回2
    return 2
end
-- 3.4 扣减库存
redis.call('incrby', stockKey, -1);
-- 3.5将userId存入当前优惠券的set集合
redis.call('sadd', orderKey, userId);
return 0